export interface RemoteChecklistInterface {
    clid: number;
    name: string;
    title: string;
    locality: string;
    publication: string;
    abstract: string;
    authors: string;
    type: string;
    politicaldivision: string;
    searchterms: string;
    parent: string;
    parentclid: number;
    notes: string;
    latcentroid: number;
    longcentroid: number;
    pointradiusmeters: number;
    footprintwkt: string;
    percenteffort: number;
    access: string;
    defaultsettings: string;
    iconurl: string;
    headerurl: string;
    uid: number;
    sortsequence: number;
    expiration: number;
    datelastmodified: string;
    initialtimestamp: number;
}
